# Image used to create a rootfs using a pacstrap-like process.
FROM scratch
ADD rootfs.tar.gz /
COPY prep-pacman.sh /
COPY qemu-arm-static /usr/bin

ENV ARCH %ARCH%
COPY mirrorlist /etc/pacman.d/mirrorlist
RUN set -xe \
 && perl -ne 'gethostbyname($1) if /^Server = https?:\/\/(.+)\//' < /etc/pacman.d/mirrorlist \
 && pacman --noconfirm -Sy archlinuxarm-keyring \
 && pacman-key --init \
 && pacman-key --populate archlinuxarm \
 && /prep-pacman.sh

COPY docker-pacstrap.sh /
ENTRYPOINT ["/docker-pacstrap.sh"]
