#!/bin/bash
# Wrapper for makepkg that sets up the environment.
set -e

# Additional settings.
keyserver="${keyserver-ha.pool.sks-keyservers.net}"

# Read the PKGBUILD.
source PKGBUILD

# Fetch PGP keys used in the build.
if (( ${#validpgpkeys[@]} > 0 )); then
    echo '==> Fetching PGP keys...'
    gpg --keyserver "${keyserver}" --recv-keys ${validpgpkeys[@]}
fi

# Update the package database if we need to install dependencies.
# Add the makepkg repository if present.
if (( ${#depends[@]} > 0 || ${#makedepends[@]} > 0 )); then
    if [ -f /repo/makepkg.db.tar.gz ]; then
        sudo docker-enable-makepkg-repo
    fi
    sudo pacman --noconfirm -Sy
fi

# Leave the rest to makepkg.
exec makepkg --noconfirm -s $@
