FROM %parent_layer%

RUN set -xe \
 && useradd -m builduser \
 && echo 'builduser ALL = NOPASSWD: /usr/bin/pacman, /usr/bin/docker-enable-makepkg-repo' \
    > /etc/sudoers.d/builduser-pacman

COPY docker-makepkg docker-enable-makepkg-repo /usr/bin/
WORKDIR /build
USER builduser
ENTRYPOINT ["docker-makepkg"]
