FROM %BASE%
RUN set -xe \
 && perl -ne 'gethostbyname($1) if /^Server = https?:\/\/(.+)\//' < /etc/pacman.d/mirrorlist \
 && pacman --noconfirm -Sy --needed base-devel \
 && rm -r /var/lib/pacman/sync /var/cache/pacman/pkg
